CREATE TABLE "HR"."SCORE_DATABASE" 
   (	"NAME" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"KOR" NUMBER(3,0) NOT NULL ENABLE, 
	"ENG" NUMBER(3,0) NOT NULL ENABLE, 
	"MATH" NUMBER(3,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("NAME")